"""adds Task model

Revision ID: 251b0ab43921
Revises: 8a639febab0e
Create Date: 2025-11-04 14:03:23.328750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '251b0ab43921'
down_revision = '8a639febab0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('completes_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completes_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
